"""Embed the entire Python backend in JS without runtime project-file dependencies."""

import base64
import hashlib
import json
from pathlib import Path
import zlib


ROOT = Path(__file__).resolve().parent


def backend_source():
    # Backend files share an isolated namespace; model SDKs are imported lazily.
    return "\n\n".join((ROOT / filename).read_text(encoding="utf-8")
                       for filename in ("model.py", "mlx_model.py", "server.py"))


def backend_bundle():
    source = backend_source()
    return (base64.b64encode(zlib.compress(source.encode("utf-8"))).decode("ascii"),
            hashlib.sha256(source.encode("utf-8")).hexdigest()[:20])


def load_backend():
    namespace = {"__name__": "_local_model_provider_backend"}
    exec(compile(backend_source(), "<pythona>", "exec"), namespace)
    return namespace


def bootstrap_source(payload, build_id, settings):
    # Encode JSON as a string literal so configuration values never become Python code.
    return (
        "import base64 as _b, zlib as _z, json as _j\n"
        "_scope = {'__name__': '_local_model_provider_backend'}\n"
        f"exec(compile(_z.decompress(_b.b64decode({payload!r})), '<pythona>', 'exec'), _scope)\n"
        f"_config = _j.loads({json.dumps(settings, ensure_ascii=False)!r})\n"
        f"print(_j.dumps(_scope['start_service'](_config, {build_id!r}), ensure_ascii=False))\n"
    )


def build_provider(settings):
    payload, build_id = backend_bundle()
    header = (
        "// Generated by Pythona AI Setup; includes the complete Python backend.\n"
        f"const BACKEND_PAYLOAD = {json.dumps(payload)};\n"
        f"const BACKEND_BUILD = {json.dumps(build_id)};\n"
        f"const DEFAULT_SETTINGS = {json.dumps(settings, ensure_ascii=False)};\n"
    )
    return header + (ROOT / "provider.js").read_text(encoding="utf-8")
